name: beijing_housing_analysis_Group_2
channels:
  - conda-forge
dependencies:
  - r-base=4.0.5
  - r-dplyr=1.1.4
  - r-ggplot2=3.5.0
  - r-tidyr=1.3.0
  - r-readr=2.1.5
  - r-corrplot=0.92
  - r-tidyverse=2.0.0
  - r-lubridate=1.9.3
  - r-repr=1.1.6
  - r-cowplot=1.1.3
  - r-ggmap=4.0.0
  - r-mapproj=1.2.11
  - r-viridis=0.6.5

