name: beijing_housing_analysis_Group_2
channels:
  - conda-forge
dependencies:
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-tidyr
  - r-readr
  - r-corrplot
  - r-tidyverse
  - r-lubridate
  - r-repr
  - r-cowplot
  - r-ggmap
  - r-mapproj
  - r-viridis
